name = "staging-env-deploy"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "staging-env-deploy_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "staging-env-deploy.wasm"
command = "npm run build:release"
